var annotated_dup =
[
    [ "AttributeInfo", "class_attribute_info.html", "class_attribute_info" ],
    [ "Classes", "class_classes.html", "class_classes" ],
    [ "ClassFile", "class_class_file.html", "class_class_file" ],
    [ "ClassLoaderSubsystem", "class_class_loader_subsystem.html", null ],
    [ "Code_attribute", "struct_code__attribute.html", "struct_code__attribute" ],
    [ "CONSTANT_Class_info", "struct_c_o_n_s_t_a_n_t___class__info.html", "struct_c_o_n_s_t_a_n_t___class__info" ],
    [ "CONSTANT_Double_info", "struct_c_o_n_s_t_a_n_t___double__info.html", "struct_c_o_n_s_t_a_n_t___double__info" ],
    [ "CONSTANT_Fieldref_info", "struct_c_o_n_s_t_a_n_t___fieldref__info.html", "struct_c_o_n_s_t_a_n_t___fieldref__info" ],
    [ "CONSTANT_Float_info", "struct_c_o_n_s_t_a_n_t___float__info.html", "struct_c_o_n_s_t_a_n_t___float__info" ],
    [ "CONSTANT_Integer_info", "struct_c_o_n_s_t_a_n_t___integer__info.html", "struct_c_o_n_s_t_a_n_t___integer__info" ],
    [ "CONSTANT_InterfaceMethodref_info", "struct_c_o_n_s_t_a_n_t___interface_methodref__info.html", "struct_c_o_n_s_t_a_n_t___interface_methodref__info" ],
    [ "CONSTANT_Long_info", "struct_c_o_n_s_t_a_n_t___long__info.html", "struct_c_o_n_s_t_a_n_t___long__info" ],
    [ "CONSTANT_Methodref_info", "struct_c_o_n_s_t_a_n_t___methodref__info.html", "struct_c_o_n_s_t_a_n_t___methodref__info" ],
    [ "CONSTANT_NameAndType_info", "struct_c_o_n_s_t_a_n_t___name_and_type__info.html", "struct_c_o_n_s_t_a_n_t___name_and_type__info" ],
    [ "CONSTANT_String_info", "struct_c_o_n_s_t_a_n_t___string__info.html", "struct_c_o_n_s_t_a_n_t___string__info" ],
    [ "CONSTANT_Utf8_info", "struct_c_o_n_s_t_a_n_t___utf8__info.html", "struct_c_o_n_s_t_a_n_t___utf8__info" ],
    [ "ConstantValue_attribute", "struct_constant_value__attribute.html", "struct_constant_value__attribute" ],
    [ "CpInfo", "class_cp_info.html", "class_cp_info" ],
    [ "ExceptionHandler", "class_exception_handler.html", "class_exception_handler" ],
    [ "Exceptions_attribute", "struct_exceptions__attribute.html", "struct_exceptions__attribute" ],
    [ "FieldInfo", "class_field_info.html", "class_field_info" ],
    [ "Frame", "class_frame.html", "class_frame" ],
    [ "InnerClasses_attribute", "struct_inner_classes__attribute.html", "struct_inner_classes__attribute" ],
    [ "Interpreter", "class_interpreter.html", "class_interpreter" ],
    [ "MemoryManager", "class_memory_manager.html", null ],
    [ "MethodAreaSection", "class_method_area_section.html", "class_method_area_section" ],
    [ "MethodInfo", "class_method_info.html", "class_method_info" ],
    [ "ObjectRef", "class_object_ref.html", "class_object_ref" ],
    [ "Opcodes", "class_opcodes.html", null ],
    [ "ReadFile", "class_read_file.html", null ],
    [ "Runtime", "class_runtime.html", "class_runtime" ],
    [ "SourceFile_attribute", "struct_source_file__attribute.html", "struct_source_file__attribute" ],
    [ "Synthetic_attribute", "struct_synthetic__attribute.html", null ],
    [ "Value", "struct_value.html", "struct_value" ]
];